FROM __BASEIMAGE_ARCH__/nginx:1.15.8-alpine
__CROSS_COPY ./multiarch/qemu-__QEMU_ARCH__-static /usr/bin/
RUN rm /etc/nginx/conf.d/*
ADD ./data/hello.conf /etc/nginx/conf.d/
ADD ./data/index.html /usr/share/nginx/html/
